### ISSUE TITLE
Redirect of MPS User guide

### ISSUE THREAD

**Issue by kschmid** [mbeddr/mps-platform-docs#11]
Not sure where it belongs (I suppose as documentation related, it is probably best here):
 on the main page of the project there is a link for the user guide. 
http://mbeddr.com/userguide/UserGuideExport.html
However, when trying to use it, one is immediately redirected to the github page. 

This is a pity, as there does not seem to be an alternative link to the user guide. Hence, it is currently, apparently inaccessible.

**Comment by alexanderpann** [comment]
I've deactivated the redirect to the GitHub page, it now works again. I guess we have to re-evaluate which pages we want to redirect or find a better solution. Thanks for letting us know.
